name: "Mantener Vivo Streamlit"

on:
  schedule:
    # Se ejecuta cada 15 minutos
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permite activarlo manualmente

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Despertar App
        run: |
          curl -I -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" https://linea-de-tiempo.streamlit.app/
